### PR TITLE
dev v0.3.6

### PR DESCRIPTION
**Pull request by dshkol**
Starting a draft to prepare this branch for next version updates and any downstream changes for the next CRAN release. 

Proposed :

1) Adding a method for precompiling vignettes. @mountainMath - have you tested this works and addresses current issues?

2) Replace deprecated dplyr/tibble function calls etc

### CODE REVIEW

**Comment by mountainMath** [comment]
I am not sure we need the precompiled vignette. We did not do anything to {cancensus} and [all the vignettes show up just fine on CRAN](https://cran.r-project.org/web/packages/cancensus/index.html). Not sure why and how, maybe that gets somehow folded in when compiling pkgdown documentation?

**Comment by dshkol** [comment]
I wasn't sure either - but leaving it to you. Are there other changes here besides the precompiled vignette that need to be incorporated? Can cherry pick those commits only.

**Comment by mountainMath** [comment]
It's been a long time coming with the precompile-vignette branch, but I am leaning toward pushing it off for another round and see if our usual process can get the vignettes precompiled just like it did not {cancensus}. The only change that was needed for {cancensus} was to add the `vignette:` field to the header and the vignettes showed up.

**Comment by dshkol** [comment]
Do you want to roll the fixe for #80 and #81 in here when they are ready?

**Pull request merged**
